### ISSUE TITLE
No More Drinking Water

### ISSUE THREAD

**Issue by SadTrappy** [LemonsHQ/Foxys-Kingdoms#7]
The thirst mod is useless and not needed just wastes more inventory space and drains way to quickly makes it way to hard to sustain and need a 27 water bottles just to sustain yourself for 20mins

**Comment by pingudestroyer** [comment]
the water system sucks ass. and if not remove i will start a strike on the server

**Comment by FoxyMcFoxon** [comment]
Not needed dumb suggestion
