### ISSUE TITLE
Separate Discord VC

### ISSUE THREAD

**Issue by YinnyGuardian** [LemonsHQ/Foxys-Kingdoms#9]
I think it would be nice to have a call for people who are wanting to either RP on the server or are wanting to record a video with roleplay aspects. That way people are not interrupting the RP if there are more than one person RPing

**Comment by FoxyMcFoxon** [comment]
I suggest ingame voice for ingame RP ;-)

**Comment by YinnyGuardian** [comment]
It doesn't work :(
